spring:
    jade4j:
        caching: true
        prettyPrint: true

    datasource:
        url: ${SPRING_DB_URL}
        username: ${SPRING_DB_USERNAME}
        password: ${SPRING_DB_PASSWORD}
        test-on-borrow: true
        remove-abandoned: true
        validation-query: 'SELECT 1'
